/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinemamovies;

import java.awt.Image;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;


/**
 *
 * @author elitebook
 */
public class Deletefromadmin extends javax.swing.JFrame {

    /**
     * Creates new form AdminDelete
     */
    public Deletefromadmin() {
        initComponents();
        jLabelProductName.setText(null);
        jLabelProductBrand.setText(null);
        jTxtDescription.setText(null);
   
        jLabelProductPrice.setText(null);
        
        jLabelImage.setText(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtProductId = new javax.swing.JTextField();
        jBtnSearch = new javax.swing.JButton();
        jLabelProductName = new javax.swing.JLabel();
        jLabelProductBrand = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtDescription = new javax.swing.JTextArea();
        jLabelProductPrice = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelImage = new javax.swing.JLabel();
        jBtnClear = new javax.swing.JButton();
        jBtnDelete = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Product ID to delete:");

        jTxtProductId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtProductIdActionPerformed(evt);
            }
        });

        jBtnSearch.setBackground(new java.awt.Color(255, 51, 51));
        jBtnSearch.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSearch.setText("Search");
        jBtnSearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnSearch.setContentAreaFilled(false);
        jBtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSearchActionPerformed(evt);
            }
        });

        jLabelProductName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelProductName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProductName.setText("<movie product name will be displayed here>");

        jLabelProductBrand.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelProductBrand.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProductBrand.setText("<movie genre will be displayed here>");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Movie Name");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Movie Genre");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Movie  Description:");

        jTxtDescription.setEditable(false);
        jTxtDescription.setBackground(new java.awt.Color(204, 204, 204));
        jTxtDescription.setColumns(20);
        jTxtDescription.setRows(5);
        jScrollPane1.setViewportView(jTxtDescription);

        jLabelProductPrice.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelProductPrice.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProductPrice.setText("<movie price will be displayed here>");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Product Price:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Product Image Name:");

        jLabelImage.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelImage.setForeground(new java.awt.Color(255, 255, 255));
        jLabelImage.setText("<movie image will be displayed here>");

        jBtnClear.setText("Clear Fields");
        jBtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClearActionPerformed(evt);
            }
        });

        jBtnDelete.setText("Delete Product");
        jBtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("B&M cinema");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel8))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnClear)
                        .addGap(37, 37, 37)
                        .addComponent(jBtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTxtProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(271, 271, 271)
                                .addComponent(jBtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelProductPrice)
                            .addComponent(jLabelProductBrand)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelImage)
                            .addComponent(jLabelProductName))))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtProductId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelProductName))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabelProductBrand))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProductPrice)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelImage)
                    .addComponent(jLabel5))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnClear)
                    .addComponent(jBtnDelete))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(900, 624));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtProductIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtProductIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtProductIdActionPerformed

    public boolean idExists(){
        boolean find = false;
        JSONParser parser = new JSONParser();
        ArrayList<String> ids = new ArrayList<>();
         try {
        JSONArray a = (JSONArray) parser.parse(new FileReader("check.json"));
        for (Object o : a)
        {
            JSONObject obj = (JSONObject) o;
            String id = (String) obj.get("id");
            ids.add(id);
           
             
            
        }
    } catch (FileNotFoundException e) {
        e.printStackTrace();
    } catch (IOException e) {
        e.printStackTrace();
    } catch (ParseException e) {
        e.printStackTrace();
    }
         for(int i=0; i<ids.size(); i++){
             if(jTxtProductId.getText().equals(ids.get(i))){
             find = true;
             }
         }
        
        
        
        return find;
    }
    private void jBtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSearchActionPerformed
       JSONParser parser = new JSONParser();
       
       if(idExists()){
           
       
       
    try {
        JSONArray a = (JSONArray) parser.parse(new FileReader("check.json"));
        for (Object o : a)
        {
            JSONObject obj = (JSONObject) o;
            if(obj.get("id").equals(jTxtProductId.getText())){
            
            jLabelProductName.setText((String) obj.get("name"));
            jLabelProductBrand.setText((String) obj.get("Genre"));
            jTxtDescription.setText((String) obj.get("description"));
          
            jLabelProductPrice.setText((String) obj.get("price"));
           
            jLabelImage.setText((String) obj.get("image"));
            
            
            }
            
            
            
        }
    } catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
       }
       else{
           JOptionPane.showMessageDialog(null, "No such product Id. Try another Id");
           clearFields();
       }
        
    }//GEN-LAST:event_jBtnSearchActionPerformed

    private void jBtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteActionPerformed
        
        JSONArray jrr = new JSONArray();
        Object ob = null;
        JSONParser Jp = new JSONParser();
        
       
        try{
            FileReader file = new FileReader("check.json");
            ob = Jp.parse(file);
            jrr=(JSONArray) ob;
            file.close();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error Occured While fetching");
        }

        JSONObject obj = new JSONObject();
        int size = jrr.size();
        
        
        
        obj.put("id", jTxtProductId.getText());
        obj.put("name", jLabelProductName.getText());
        obj.put("Genre", jLabelProductBrand.getText());
        obj.put("description", jTxtDescription.getText());
       
        obj.put("price", jLabelProductPrice.getText());
        
        obj.put("image", jLabelImage.getText());
                
        
        for(int i=0; i<size; i++){
            if(obj.equals(jrr.get(i))){
                try{
                    FileWriter file =  new FileWriter("check.json");
                    jrr.remove(i);
                    file.write(jrr.toJSONString());
                    file.close();
                } catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Error Occured");
        }
                JOptionPane.showMessageDialog(null, "Data Removed");
                clearFields();
                break;
        }else if(i==size-1){
            JOptionPane.showMessageDialog(null, "Incorrect details entered");
        }
    }         
        
        
    }//GEN-LAST:event_jBtnDeleteActionPerformed

    private void jBtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClearActionPerformed
        clearFields();
    }//GEN-LAST:event_jBtnClearActionPerformed

    public void clearFields(){
            jTxtProductId.setText(null);
            jLabelProductName.setText(null);
            jLabelProductBrand.setText(null);
            jTxtDescription.setText(null);
           
            jLabelProductPrice.setText(null);
            
            jLabelImage.setText(null);
    }
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnClear;
    private javax.swing.JButton jBtnDelete;
    private javax.swing.JButton jBtnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelProductBrand;
    private javax.swing.JLabel jLabelProductName;
    private javax.swing.JLabel jLabelProductPrice;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTxtDescription;
    private javax.swing.JTextField jTxtProductId;
    // End of variables declaration//GEN-END:variables
}
