/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cinemamovies;

/**
 *
 * @author manoo
 */
import java.awt.BorderLayout;
import java.awt.Button;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Arrays;

import javax.accessibility.AccessibleContext;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class login1 extends javax.swing.JFrame implements ActionListener {
    
    

   
    public login1() {
        JFrame frame = new JFrame ();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
        
        initComponents();
        load();
    }

   
    public void load(){
       
        btnlogin.addActionListener(this);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        my_list3 = new javax.swing.JLabel();
        usernameText = new javax.swing.JTextField();
        PasswordText = new javax.swing.JPasswordField();
        btnlogin = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        home1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(19, 18, 18));
        jPanel1.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(240, 240, 240));
        jLabel18.setText("Login/Register");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(370, 450, 120, 20);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(240, 240, 240));
        jLabel21.setText("Constumer care");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(120, 450, 110, 20);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(240, 240, 240));
        jLabel23.setText("About us");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(270, 450, 70, 20);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(null);

        home.setFont(new java.awt.Font("Segoe UI Semilight", 1, 11)); // NOI18N
        home.setForeground(new java.awt.Color(240, 240, 240));
        home.setText("Login using your  username and password.");
        jPanel3.add(home);
        home.setBounds(140, 70, 250, 40);
        home.getAccessibleContext().setAccessibleParent(home
        );

        my_list3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 13)); // NOI18N
        my_list3.setForeground(new java.awt.Color(240, 240, 240));
        my_list3.setText("password");
        my_list3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        my_list3.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
        my_list3.setDoubleBuffered(true);
        my_list3.setFocusCycleRoot(true);
        my_list3.setFocusTraversalPolicyProvider(true);
        my_list3.setName(""); // NOI18N
        my_list3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                my_list3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                my_list3FocusLost(evt);
            }
        });
        my_list3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                my_list3MouseClicked(evt);
            }
        });
        jPanel3.add(my_list3);
        my_list3.setBounds(50, 160, 60, 32);

        usernameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextActionPerformed(evt);
            }
        });
        jPanel3.add(usernameText);
        usernameText.setBounds(150, 130, 200, 20);

        PasswordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextActionPerformed(evt);
            }
        });
        jPanel3.add(PasswordText);
        PasswordText.setBounds(150, 170, 200, 20);

        btnlogin.setBackground(new java.awt.Color(0, 0, 0));
        btnlogin.setForeground(new java.awt.Color(240, 240, 240));
        btnlogin.setText("LOGIN");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        jPanel3.add(btnlogin);
        btnlogin.setBounds(260, 220, 100, 30);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(240, 240, 240));
        jLabel25.setText("Movies");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(620, 380, 120, 20);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(240, 240, 240));
        jLabel24.setText("Cinema Location");
        jPanel3.add(jLabel24);
        jLabel24.setBounds(260, 400, 120, 20);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(240, 240, 240));
        jLabel22.setText("Home");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(80, 400, 70, 20);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Snap ITC", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("B&M cinema");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(150, -30, 420, 140);

        home1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 13)); // NOI18N
        home1.setForeground(new java.awt.Color(240, 240, 240));
        home1.setText("Username");
        jPanel3.add(home1);
        home1.setBounds(50, 120, 80, 32);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 10, 570, 330);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void my_list3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_my_list3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_my_list3FocusGained

    private void my_list3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_my_list3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_my_list3FocusLost

    private void my_list3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_my_list3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_my_list3MouseClicked

    private void usernameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextActionPerformed

    private void PasswordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_btnloginActionPerformed

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cinemadesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cinemadesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cinemadesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cinemadesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cinemadesign().setVisible(true);
            }
        });
    }
*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordText;
    private javax.swing.JButton btnlogin;
    private javax.swing.JLabel home;
    private javax.swing.JLabel home1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel my_list3;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables

    
    public void actionPerformed(ActionEvent e) {
        
        String uName, pwd;
        if(e.getSource() == btnlogin){  
          
        //System.out.println("Connect to profile");
        
        String username = this.usernameText.getText();
        String password = this.PasswordText.getText();
       
        
        connectinglogin conn = new connectinglogin(username,password);
        conn.Connection();
            
           uName = this.usernameText.getText();
            pwd = Arrays.toString(this.PasswordText.getPassword());
            
            
            
        }
        else 
            JOptionPane.showMessageDialog(null, " wrong username/password");
            
        
        
        
            
    }
}
