/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinemamovies;

import java.awt.Image;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import cinemamovies.Products;
import org.json.simple.parser.ParseException;

/**
 *
 * @author elitebook
 */
public class Moviemain extends javax.swing.JFrame {


    
    public Moviemain() {
        initComponents();
        for(int i=1;i<=100;i++) 
            {
            combobox.addItem(new Integer(i).toString());
            
            }
       
        imagelabel.setText(null);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        combobox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        moviename = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        moviegenre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        moviedescription = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        movieprice = new javax.swing.JTextField();
        browseimage = new javax.swing.JButton();
        jTxtBrowseImage = new javax.swing.JTextField();
        jBtnAddProduct = new javax.swing.JButton();
        jBtnClear = new javax.swing.JButton();
        jBtnGoBack = new javax.swing.JButton();
        imagelabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Movie ID:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Movie Name:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Genre:");

        moviegenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moviegenreActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Movie Description:");

        moviedescription.setColumns(20);
        moviedescription.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        moviedescription.setRows(5);
        moviedescription.setBorder(null);
        jScrollPane1.setViewportView(moviedescription);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Price:");

        movieprice.setText("$");

        browseimage.setBackground(new java.awt.Color(255, 51, 51));
        browseimage.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        browseimage.setForeground(new java.awt.Color(255, 255, 255));
        browseimage.setText("Upload Images");
        browseimage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        browseimage.setContentAreaFilled(false);
        browseimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseimageActionPerformed(evt);
            }
        });

        jTxtBrowseImage.setEditable(false);
        jTxtBrowseImage.setBackground(new java.awt.Color(153, 153, 153));
        jTxtBrowseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtBrowseImageActionPerformed(evt);
            }
        });

        jBtnAddProduct.setBackground(new java.awt.Color(255, 51, 51));
        jBtnAddProduct.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnAddProduct.setForeground(new java.awt.Color(255, 255, 255));
        jBtnAddProduct.setText("Add Product");
        jBtnAddProduct.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnAddProduct.setContentAreaFilled(false);
        jBtnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddProductActionPerformed(evt);
            }
        });

        jBtnClear.setBackground(new java.awt.Color(255, 51, 51));
        jBtnClear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnClear.setForeground(new java.awt.Color(255, 255, 255));
        jBtnClear.setText("Clear");
        jBtnClear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnClear.setContentAreaFilled(false);
        jBtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClearActionPerformed(evt);
            }
        });

        jBtnGoBack.setBackground(new java.awt.Color(255, 51, 51));
        jBtnGoBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnGoBack.setForeground(new java.awt.Color(255, 255, 255));
        jBtnGoBack.setText("Back");
        jBtnGoBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnGoBack.setContentAreaFilled(false);
        jBtnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGoBackActionPerformed(evt);
            }
        });

        imagelabel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("B&M cinema");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(58, 58, 58))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                        .addGap(53, 53, 53))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(movieprice, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jBtnAddProduct)
                                        .addGap(33, 33, 33)
                                        .addComponent(jBtnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(jBtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(moviegenre)
                                                .addComponent(moviename)
                                                .addComponent(combobox, 0, 186, Short.MAX_VALUE))
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(61, 61, 61)
                                        .addComponent(browseimage, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTxtBrowseImage, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(imagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(368, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(browseimage)
                    .addComponent(jTxtBrowseImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(moviename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(moviegenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(imagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(movieprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAddProduct)
                    .addComponent(jBtnGoBack)
                    .addComponent(jBtnClear))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(870, 541));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddProductActionPerformed
        
        JSONObject obj = new JSONObject();
        JSONArray jrr = new JSONArray();
        JSONParser jp = new JSONParser();
        String na = moviename.getText();
        String ah = moviegenre.getText();
        String ba = moviedescription.getText();
        if(na.isEmpty()|| ah.isEmpty()||ba.isEmpty()){
               JOptionPane.showMessageDialog(null, "Please enter the field below" );
               
        }else{
        if(idExists())
        {
            JOptionPane.showMessageDialog(null, "Id already stored please check another ");
        }
        else{
        try{
            FileReader file = new FileReader("check.json");
            jrr = (JSONArray) jp.parse(file);
        }
            catch(Exception ex)
                    {
                        JOptionPane.showMessageDialog(null, "Error Occured");
                    }
        
        obj.put("id", combobox.getSelectedItem());
        obj.put("name", moviename.getText());
        obj.put("Genre", moviegenre.getText());
        obj.put("description", moviedescription.getText());
       
        obj.put("image", imagelabel.getText());
        
        jrr.add(obj);
        try{
            FileWriter file =  new FileWriter("check.json");
            file.write(jrr.toJSONString());
            file.close();
            
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error Occured");
        }
        try{
            Path source = Paths.get(jTxtBrowseImage.getText());
            Path targetDir = Paths.get("C:\\Users\\manoo\\Videos\\Matrix\\images");
            Path target = targetDir.resolve(imagelabel.getText());
            Files.copy(source, target, StandardCopyOption.REPLACE_EXISTING);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
        }
        JOptionPane.showMessageDialog(null, "movie added");
        clearFields();
        }
        }
    }//GEN-LAST:event_jBtnAddProductActionPerformed

    public boolean idExists(){
        boolean condition = false;
        JSONParser parser = new JSONParser();
        ArrayList<String> ids = new ArrayList<>();
         try {
        JSONArray a = (JSONArray) parser.parse(new FileReader("check.json"));
        for (Object o : a)
        {
            JSONObject obj = (JSONObject) o;
            String id = (String) obj.get("id");
            ids.add(id);
           
             
            
        }
    } catch (FileNotFoundException e) {
        e.printStackTrace();
    } catch (IOException e) {
        e.printStackTrace();
    } catch (ParseException e) {
        e.printStackTrace();
    }
         for(int i=0; i<ids.size(); i++){
             if(combobox.getSelectedItem().equals(ids.get(i))){
             condition = true;
             }
         }
        
        
        
        return condition;
    }
    private void browseimageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseimageActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String fileName = f.getAbsolutePath();
        String filesss = f.getName();
        imagelabel.setText(filesss);
        
        jTxtBrowseImage.setText(fileName);
        ImageIcon img = new ImageIcon(new ImageIcon(fileName).getImage().getScaledInstance(60, 60, Image.SCALE_DEFAULT));
         
        imagelabel.setIcon(img);
        
        
    }//GEN-LAST:event_browseimageActionPerformed

    private void jBtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClearActionPerformed
        clearFields();
        combobox.requestFocus();
    }//GEN-LAST:event_jBtnClearActionPerformed

    private void jBtnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGoBackActionPerformed
        dispose();
        Products a1 = new Products("");
        a1.setVisible(true);
        
    }//GEN-LAST:event_jBtnGoBackActionPerformed

    private void jTxtBrowseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtBrowseImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtBrowseImageActionPerformed

    private void moviegenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moviegenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moviegenreActionPerformed
     public void clearFields(){
         combobox.setSelectedItem(null);
         moviename.setText(null);
         moviegenre.setText(null);
         moviedescription.setText(null);
         buttonGroup1.clearSelection();
         moviename.setText(null);
         movieprice.setText(null);
        
         jTxtBrowseImage.setText(null);
         imagelabel.setIcon(null);
     }
    /**
     * @param args the command line arguments
     */
     
   
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseimage;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JLabel imagelabel;
    private javax.swing.JButton jBtnAddProduct;
    private javax.swing.JButton jBtnClear;
    private javax.swing.JButton jBtnGoBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtBrowseImage;
    private javax.swing.JTextArea moviedescription;
    private javax.swing.JTextField moviegenre;
    private javax.swing.JTextField moviename;
    private javax.swing.JTextField movieprice;
    // End of variables declaration//GEN-END:variables
}
